name: Smuggler Scan

on:
  push:
    branches: [master]

jobs:
  smuggle-scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout kode repositori
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install dependencies untuk Smuggler
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git

      # 3. Clone repositori Smuggler
      - name: Clone Smuggler repository
        run: |
          git clone https://github.com/defparam/smuggler.git
          cd smuggler

      # 4. Jalankan Smuggler dan simpan hasilnya
      - name: Run Smuggler scan
        run: |
          cd smuggler
          curl -s "https://gist.githubusercontent.com/z0rs/5e3e2a08a0a9d0fa432b028e18f5d304/raw/c4be0799eefab299dee56762e9893c46fc3e4143/detrip" | python3 smuggler.py > ../smuggler-results.txt

      # 5. Konfigurasi Git user untuk commit hasil scan
      - name: Set up Git user
        run: |
          git config --global user.email "${{ secrets.EMAIL_ADDRESS }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      # 6. Commit hasil scan ke repositori
      - name: Commit changes
        run: |
          git add smuggler-results.txt
          git commit -m "Smuggler scan results $(date -u)" --no-verify || echo "No changes to commit"

      # 7. Push hasil scan ke repositori
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

      
